public enum EventKey
{
    NONE = -1,
    STARTGAME,
    ENDGAME,
    UPDATE_UI,
    CABINET_DOOR_OPEN,
    SAFE_AREA_ENTER,
    SAFE_AREA_EXIT,
    UNSHIELD_WALL,
    PLAYER_SCALE_UP,
    TURN_ON_ELECTRICITY,
    LOAD_NEXT_LEVEL,
    LOAD_CURRENT_LEVEL,
}